(function(){
  function init(){
    var trigger=document.querySelector('a.back-btn, a.back'),header=trigger&&trigger.closest('header');
    if(!trigger||!header)return;
    var button=document.createElement('button');button.type='button';button.className='hub-menu-trigger';button.setAttribute('aria-label','메뉴 열기');button.textContent='☰ 메뉴';
    var topbar=document.createElement('div');topbar.className='hub-topbar';topbar.innerHTML='<div class="hub-brand"><img src="logo.png" alt="도개중고등학교 로고"><div><b>도개중고등학교 정보 허브</b><small>DO GAE MIDDLE · HIGH SCHOOL</small></div></div><div class="hub-topbar-right"><span class="hub-date"></span></div>';
    topbar.querySelector('.hub-date').textContent=new Date().toLocaleDateString('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'});
    var right=topbar.querySelector('.hub-topbar-right'),sourceLogo=header.querySelector('#logoWrap');
    var tools=header.querySelector('.header-right');
    if(tools){Array.from(tools.children).forEach(function(el){if(!el.matches('.logo-wrap,.header-logo'))right.appendChild(el)})}
    var deptTotal=header.querySelector('.dept-total');
    if(deptTotal)right.appendChild(deptTotal);
    var history=header.querySelector('#btnLoadHistory');
    if(history)right.appendChild(history);
    right.appendChild(button);header.before(topbar);trigger.remove();header.style.display='none';
    var pageNames={'mindmap.html':'업무분장','career.html':'진로 활동 탐색기','seating.html':'자리 배치표','forms.html':'양식 자료실'};
    var pageName=pageNames[location.pathname.split('/').pop()];
    if(pageName){var sectionTitle=document.createElement('div');sectionTitle.className='hub-section-title';sectionTitle.innerHTML='<h1>'+pageName+'</h1>';topbar.after(sectionTitle)}
    if(sourceLogo)topbar.querySelector('.hub-brand').addEventListener('click',function(){sourceLogo.click()});
    var style=document.createElement('style');style.textContent='.hub-topbar{height:68px;background:rgba(255,255,255,.94);backdrop-filter:blur(14px);border-bottom:1px solid #DCE2F0;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(16px,4vw,52px);position:sticky;top:0;z-index:850;font-family:"Noto Sans KR",sans-serif}.hub-brand{display:flex;align-items:center;gap:11px}.hub-brand img{width:38px;height:38px;object-fit:contain}.hub-brand b{display:block;font-family:"Noto Serif KR",serif;font-size:17px;color:#17245D}.hub-brand small{display:block;font-size:10px;letter-spacing:.08em;color:#68748A;margin-top:1px}.hub-topbar-right{display:flex;align-items:center;gap:10px}.hub-date{font-size:12px;color:#68748A}.hub-menu-trigger{height:34px;border:1px solid #DCE2F0;border-radius:10px;background:#fff;color:#253E8A;padding:0 12px;font:700 12px "Noto Sans KR",sans-serif;cursor:pointer}.hub-menu-trigger:hover{background:#EEF2FB}.hub-section-title{height:52px;flex:none;display:flex;align-items:center;padding:0 clamp(16px,4vw,52px);background:#fff;border-bottom:1px solid #E2E8F4}.hub-section-title h1{margin:0;color:#17245D;font:700 20px "Noto Serif KR",serif}.hub-nav-shade{position:fixed;inset:0;background:rgba(12,24,58,.38);z-index:900;opacity:0;pointer-events:none;transition:.2s}.hub-nav-shade.open{opacity:1;pointer-events:auto}.hub-nav{position:fixed;right:0;top:0;bottom:0;width:min(330px,88vw);background:#fff;z-index:901;padding:25px;box-shadow:-16px 0 45px rgba(12,24,58,.2);transform:translateX(100%);transition:.24s;font-family:"Noto Sans KR",sans-serif}.hub-nav.open{transform:translateX(0)}.hub-nav-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px;color:#182B6A;font-family:"Noto Serif KR",serif;font-size:19px}.hub-nav-close{width:34px;height:34px;border:0;border-radius:9px;background:#EEF2FB;color:#253E8A;font-size:22px;cursor:pointer}.hub-nav a{display:flex;gap:12px;align-items:center;padding:13px 11px;border-radius:10px;text-decoration:none;color:#1A1E2E;font-size:14px}.hub-nav a:hover{background:#EEF2FB;color:#253E8A}@media(max-width:520px){.hub-date{display:none}.hub-brand b{font-size:14px}.hub-brand small{font-size:8px}.hub-section-title{height:46px}.hub-section-title h1{font-size:18px}}';document.head.appendChild(style);
    var shade=document.createElement('div');shade.className='hub-nav-shade';var nav=document.createElement('aside');nav.className='hub-nav';nav.innerHTML='<div class="hub-nav-head">메뉴 <button class="hub-nav-close">×</button></div><a href="index.html">▣&nbsp; 캘린더</a><a href="links.html">🔗&nbsp; 링크 모음</a><a href="mindmap.html">🧭&nbsp; 업무분장</a><a href="career.html">🌱&nbsp; 진로 활동 탐색기</a><a href="seating.html">▦&nbsp; 자리 배치표</a><a href="forms.html">▤&nbsp; 양식 자료실</a>';document.body.append(shade,nav);
    function toggle(open){shade.classList.toggle('open',open);nav.classList.toggle('open',open)}button.onclick=function(){toggle(true)};shade.onclick=function(){toggle(false)};nav.querySelector('button').onclick=function(){toggle(false)};
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
